### ISSUE TITLE
Support for alternatives to the tape command

### ISSUE THREAD

**Issue by jtlapp** [substack/faucet#19]
I've written an alternative to the `tape` and would like to be able to use it with `faucet`. The command is called [`tapeo`](https://www.npmjs.com/package/tapeo). It is presently a fork of `tape`, but it's written so that it proposes hooks in `tape` that would allow `tapeo` to simply be an executable script that uses the `tape` module.

To use `faucet` with `tapeo` or other alternative TAP producers, this is all that's needed:
- Allow an environment variable to specify the underlying TAP command.
- Pass command line options (e.g. `-n`) to the underlying TAP command.

I propose the environment variable `FAUCET_TAP_CMD`. I'll provide a PR shortly.

**Comment by revelt** [comment]
How is it going with this project?

**Comment by jtlapp** [comment]
I couldn't get it to work without having to fork my own version of `tape`, which I found fragile to my modifications anyway. `faucet` also cannot be updated to the most recent version of [`tap-parser`](https://github.com/tapjs/tap-parser) due to major changes in `tap-parser`.

So I wrote [`subtap`](https://github.com/jtlapp/subtap) instead, basing it on the `tape`-compatible test harness called [`tap`](https://github.com/tapjs/node-tap), which I was able to leverage without modification. `subtap` works fine, just a few things to wrap up.

I'm closing this issue, because `faucet` just isn't suitable for expansion this way.

**Comment by substack** [comment]
You can pipe tap into faucet.

**Comment by jtlapp** [comment]
My tools `tapeo` and `subtap` modify the behavior of the test harness. Piping isn't an option.

 `tapeo` required forking `tape` and hence replacing `tape` within `faucet`. `subtap` didn't require forking `tap` -- `tap` is flexible -- so I went that route and gave it the option for `faucet`-like output.
